# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1status', models.CharField(max_length=1)),
                ('team2status', models.CharField(max_length=1)),
                ('team3status', models.CharField(max_length=1)),
                ('team4status', models.CharField(max_length=1)),
                ('team5status', models.CharField(max_length=1)),
                ('team6status', models.CharField(max_length=1)),
                ('team7status', models.CharField(max_length=1)),
                ('team8status', models.CharField(max_length=1)),
            ],
        ),
    ]
