# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzleTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'N'), ('W', 'W'), ('C', 'C')], default='N', max_length=1)),
                ('puzz', models.PositiveSmallIntegerField()),
                ('team', models.PositiveSmallIntegerField()),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
    ]
